#!/usr/bin/env bash
# P4.5 — Idempotent tenant onboarding scaffold.
# Usage:
#   scripts/provision-tenant.sh <tenant-id> <profile> <port> [--dry-run]
# Profiles: culture | ausmaker | generic
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TENANT="${1:?usage: provision-tenant.sh <tenant-id> <profile> <port> [--dry-run]}"
PROFILE="${2:?profile required (culture|ausmaker|generic)}"
PORT="${3:?port required}"
DRY_RUN=0
if [[ "${4:-}" == "--dry-run" ]]; then DRY_RUN=1; fi

case "$PROFILE" in
  culture|ausmaker|generic) ;;
  *) echo "unknown profile: $PROFILE (culture|ausmaker|generic)" >&2; exit 1 ;;
esac

SITE_DIR="$ROOT/sites/$TENANT"
KNOW_DIR="$ROOT/knowledge/$TENANT"
ONTOLOGY_SRC="$ROOT/webchat-piko/config/ontology"
# Culture dress rehearsal / new culture tenants seed the synthetic pack (isolated
# threads/aliases from live EI culture.json). AusMaker falls back to culture pack
# until a dedicated ausmaker ontology exists.
ONTOLOGY_DST_NAME="culture.json"
if [[ "$PROFILE" == "culture" ]]; then ONTOLOGY_DST_NAME="synthetic-culture.json"; fi
if [[ "$PROFILE" == "ausmaker" ]]; then ONTOLOGY_DST_NAME="culture.json"; fi
UNIT_WEB="piko-webchat-${TENANT}.service"
UNIT_WORKER="piko-worker-${TENANT}.service"
DEPLOY_CONF="$ROOT/scripts/webchat-deploy/tenants.conf"
REG="$ROOT/legion-tenants/registry.json"
ENV_EXAMPLE="$ROOT/webchat-piko/.env.example"

plan() { echo "  - $*"; }

echo "== provision-tenant $TENANT profile=$PROFILE port=$PORT dry_run=$DRY_RUN"
echo "-- plan"
plan "site: $SITE_DIR/site.yaml (+ smoke.json)"
plan "knowledge: $KNOW_DIR/manifest.json"
plan "ontology copy: config/ontology/$ONTOLOGY_DST_NAME → sites/$TENANT/ontology.json (seed)"
plan "generate distinct API/YOLO/health/webhook/admin keys"
plan "write .env.template → sites/$TENANT/env.template (operator copies to host)"
plan "systemd unit templates → scripts/webchat-deploy/$UNIT_WEB + $UNIT_WORKER"
plan "tenants.conf entry (if missing)"
plan "registry row status=planned (if missing)"
plan "next: deploy-tenant-spine / release.sh $TENANT → eval-gate"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "-- dry-run complete (no writes)"
  exit 0
fi

mkdir -p "$SITE_DIR" "$KNOW_DIR" "$ROOT/scripts/webchat-deploy"

# Site + knowledge (reuse template when present; idempotent)
if [[ ! -f "$SITE_DIR/site.yaml" ]]; then
  if [[ -f "$ROOT/sites/_template/site.yaml" ]]; then
    sed -e "s/REPLACE_TENANT_ID/$TENANT/g" \
        -e "s/REPLACE_DISPLAY_NAME/$TENANT/g" \
        -e "s/REPLACE_BUSINESS_UNIT/$TENANT/g" \
        -e "s/REPLACE_ADAPTER_ID/${TENANT}-adapter/g" \
        -e "s/REPLACE_DOMAIN/example.com/g" \
        -e "s/REPLACE_WAN_IP/0.0.0.0/g" \
        -e "s/REPLACE_NODE_HOST/unassigned/g" \
        "$ROOT/sites/_template/site.yaml" > "$SITE_DIR/site.yaml"
  else
    cat > "$SITE_DIR/site.yaml" <<YAML
tenant_id: $TENANT
display_name: $TENANT
status: planned
host: unassigned
piko_port: $PORT
profile: $PROFILE
YAML
  fi
  echo "wrote $SITE_DIR/site.yaml"
else
  echo "keep existing $SITE_DIR/site.yaml"
fi

if [[ ! -f "$SITE_DIR/smoke.json" && -f "$ROOT/sites/_template/smoke.json" ]]; then
  sed -e "s/REPLACE_TENANT_ID/$TENANT/g" \
      -e "s/REPLACE_DISPLAY_NAME/$TENANT/g" \
      -e "s/REPLACE_ADAPTER_ID/${TENANT}-adapter/g" \
      -e "s/REPLACE_SMOKE_CAPABILITY/health.check/g" \
      "$ROOT/sites/_template/smoke.json" > "$SITE_DIR/smoke.json"
fi

if [[ ! -f "$KNOW_DIR/manifest.json" ]]; then
  if [[ -f "$ROOT/knowledge/customer-03/manifest.json" && "$PROFILE" == "culture" ]]; then
    cp "$ROOT/knowledge/customer-03/manifest.json" "$KNOW_DIR/manifest.json"
  elif [[ -f "$ROOT/knowledge/_template/manifest.json" ]]; then
    cp "$ROOT/knowledge/_template/manifest.json" "$KNOW_DIR/manifest.json"
  else
    printf '%s\n' "{\"tenant_id\":\"$TENANT\",\"profile\":\"$PROFILE\"}" > "$KNOW_DIR/manifest.json"
  fi
  echo "wrote $KNOW_DIR/manifest.json"
fi

# Ontology seed
if [[ -f "$ONTOLOGY_SRC/$ONTOLOGY_DST_NAME" && ! -f "$SITE_DIR/ontology.json" ]]; then
  cp "$ONTOLOGY_SRC/$ONTOLOGY_DST_NAME" "$SITE_DIR/ontology.json"
  echo "wrote $SITE_DIR/ontology.json"
fi

# Fresh keys
API_KEY="$(openssl rand -hex 24)"
YOLO_KEY="$(openssl rand -hex 24)"
HEALTH_KEY="$(openssl rand -hex 24)"
WEBHOOK_KEY="$(openssl rand -hex 24)"
ADMIN_PASS="$(openssl rand -hex 16)"

BG_PROFILE="shared"
[[ "$PROFILE" == "culture" ]] && BG_PROFILE="culture"
[[ "$PROFILE" == "ausmaker" ]] && BG_PROFILE="ausmaker"

ENV_OUT="$SITE_DIR/env.template"
{
  echo "# Generated by provision-tenant.sh for $TENANT — copy to host spine .env"
  echo "PORT=$PORT"
  echo "PIKO_TENANT_ID=$TENANT"
  echo "PIKO_DATA_DIR=/home/chief/data/$TENANT"
  echo "PIKO_KNOWLEDGE_PATH=/home/chief/knowledge/$TENANT"
  echo "PIKO_SITE_MANIFEST=/home/chief/sites/$TENANT/site.yaml"
  echo "PIKO_BACKGROUND_JOBS_PROFILE=$BG_PROFILE"
  echo "PIKO_API_AUTH=strict"
  echo "PIKO_ENV_STRICT=1"
  echo "PIKO_WORKER_STANDALONE=1"
  echo "PIKO_AGENT_ORCH=1"
  echo "PIKO_AGENT_WORKER=1"
  echo "PIKO_OLLAMA_ONLY=1"
  echo "PIKO_OLLAMA_QUEUE=1"
  # Point at the GPU inference host (muscle rig). The local 127.0.0.1 Ollama on
  # Optimus is CPU-only and times out on real ontology-context prompts (c04 incident 2026-08-05).
  echo "OLLAMA_URL=http://192.168.0.190:11434"
  echo "OLLAMA_MODEL=llama3.1:8b"
  echo "PIKO_LEGATE_MODEL=llama3.1:8b"
  echo "PIKO_UNDERSTAND_MODEL=llama3.1:8b"
  echo "PIKO_HEAVY_MODEL=llama3.1:8b"
  echo "TZ=Australia/Sydney"
  echo "PIKO_ADMIN_USER=admin"
  echo "PIKO_ADMIN_PASSWORD=$ADMIN_PASS"
  echo "PIKO_API_KEY=$API_KEY"
  echo "PIKO_YOLO_API_KEY=$YOLO_KEY"
  echo "PIKO_HEALTH_API_KEY=$HEALTH_KEY"
  echo "PIKO_WEBHOOK_SECRET=$WEBHOOK_KEY"
  if [[ -f "$ENV_EXAMPLE" ]]; then
    echo ""
    echo "# --- reference keys from .env.example (uncomment/adapt) ---"
  fi
} > "$ENV_OUT"
chmod 600 "$ENV_OUT"
echo "wrote $ENV_OUT (mode 600)"

# Seed secretsStore-shaped files under site for operator to copy into PIKO_DATA_DIR/secrets/
SECRETS_SEED="$SITE_DIR/secrets-seed"
mkdir -p "$SECRETS_SEED"
python3 - <<PY
import json, pathlib
base = pathlib.Path("$SECRETS_SEED")
for name, val in [
    ("api-key", "$API_KEY"),
    ("webhook", "$WEBHOOK_KEY"),
]:
    p = base / f"{name}.json"
    p.write_text(json.dumps({"current": val}, indent=2) + "\n")
    p.chmod(0o600)
print("wrote secrets-seed api-key + webhook")
PY

# Systemd unit templates
cat > "$ROOT/scripts/webchat-deploy/$UNIT_WEB" <<EOF
[Unit]
Description=Piko webchat tenant $TENANT
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/chief/webchat-piko-$TENANT
EnvironmentFile=-/home/chief/webchat-piko-$TENANT/.env
ExecStart=/usr/bin/node /home/chief/webchat-piko-$TENANT/server.js
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF

cat > "$ROOT/scripts/webchat-deploy/$UNIT_WORKER" <<EOF
[Unit]
Description=Piko agent worker ($TENANT)
After=network.target
Wants=$UNIT_WEB

[Service]
Type=simple
WorkingDirectory=/home/chief/webchat-piko-$TENANT
ExecStart=/usr/bin/node scripts/agent-worker.js
Restart=on-failure
RestartSec=5
Environment=PIKO_AGENT_ORCH=1
Environment=PIKO_WORKER_STANDALONE=1
EnvironmentFile=-/home/chief/webchat-piko-$TENANT/.env

[Install]
WantedBy=default.target
EOF
echo "wrote unit templates $UNIT_WEB $UNIT_WORKER"

# tenants.conf entry
if ! grep -q "[[:space:]]${TENANT})" "$DEPLOY_CONF" 2>/dev/null; then
  # Insert before the default *) unknown branch
  python3 - <<PY
from pathlib import Path
p = Path("$DEPLOY_CONF")
text = p.read_text()
block = '''    {tenant})
      T_HOST="optimus-wan"
      T_ROOT_HOST="optimus-wan"
      T_DIR="/home/chief/webchat-piko-{tenant}"
      T_SERVICE="piko-webchat-{tenant}.service"
      T_WORKER_SERVICE="piko-worker-{tenant}.service"
      T_SERVICE_SCOPE="user"
      T_PORT={port}
      T_HEALTH_URL="http://127.0.0.1:{port}/api/health"
      ;;
'''.format(tenant="$TENANT", port="$PORT")
needle = '    *)\n'
if block.strip().split('\n')[0] in text:
    print("tenants.conf already has $TENANT")
elif needle in text:
    p.write_text(text.replace(needle, block + needle, 1))
    print("appended $TENANT to tenants.conf")
else:
    print("WARN: could not patch tenants.conf — add manually")
PY
else
  echo "tenants.conf already references $TENANT"
fi

# Registry row
python3 - <<PY
import json
from pathlib import Path
p = Path("$REG")
data = {"tenants": []}
if p.exists():
    data = json.loads(p.read_text())
ids = {t.get("tenant_id") for t in data.get("tenants", [])}
if "$TENANT" not in ids:
    data.setdefault("tenants", []).append({
        "tenant_id": "$TENANT",
        "display_name": "$TENANT",
        "status": "planned",
        "observe_url": None,
        "adapter_id": "${TENANT}-adapter",
        "node_host": "unassigned",
        "profile": "$PROFILE",
        "piko_port": int("$PORT"),
        "setup_checklist": {
            "scaffold": True,
            "adapter": False,
            "node": False,
            "spine": False,
            "observe": False,
            "live": False,
        },
    })
    p.write_text(json.dumps(data, indent=2) + "\n")
    print("added $TENANT to registry (planned)")
else:
    print("registry already has $TENANT")
PY

echo ""
echo "== provisioned $TENANT"
echo "Handover checklist:"
echo "  1. Review $ENV_OUT (contains secrets — do not commit)"
echo "  2. Deploy spine: ./scripts/deploy-tenant-spine-optimus.sh $TENANT $PORT <adapter_port>"
echo "     or rsync + install units from scripts/webchat-deploy/"
echo "  3. Copy env.template → host .env; copy secrets-seed → \$PIKO_DATA_DIR/secrets/"
echo "  4. bash scripts/webchat-deploy/release.sh $TENANT"
echo "  5. bash scripts/webchat-deploy/eval-gate.sh $TENANT"
echo "  6. Set registry status=live + observe_url when healthy"
echo "  7. Ensure env.template / secrets-seed stay out of git (.gitignore)"
